### ISSUE TITLE
brewed cppad on mac

### ISSUE THREAD

**Issue by HTuennermann** [udacity/CarND-MPC-Project#1]
the version of cppad brew installs seems to be different from the one this was tested with [(homebrew/science/cppad: stable 20150000 (bottled), HEAD)] in the sense that:

cppad.h is called cppad.hpp (just a warning in the compiler)

and 

auto cost = solution.objvalue; in line 100 of MPC.cpp causes an error. My guess would be that it needs to be replaced by:
auto cost = solution.obj_value;

it would be cool if this can somehow be made compatible with both to avoid confusion at the review stage.

**Comment by domluna** [comment]
@HTuennermann I'll take a look at other versions, thanks for bringing this up. If anything it might be better to use 2017 version.

**Comment by domluna** [comment]
Turns out even in older versions `.hpp` is available so might as well just default to that. Also changed to `objvalue` to `obj_value`.
