### ISSUE TITLE
install_ipopt.sh: line 46: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by ajeet-repos** [udacity/CarND-MPC-Project#10]
When I try to run to install ipopt on linux subsystem in windows 10 i am getting this error. Command i tried to execute:

sudo bash install_ipopt.sh Ipopt-3.12.8/

I have unzipped the source in project base directory itself.

**Comment by ajeet-repos** [comment]
It's a windows specific issues. following action helped get it resolved:

1. Install doc to unix to convert to unix formatting:
`sudo apt-get install dos2unix`

2. Convert the install_ipopt.sh
`dos2unix install_ipopt.sh`

**Comment by zypchenfeng** [comment]
Had the same issue. Thanks a lot for the solution!!!

**Comment by QianYu92** [comment]
Same issue working on windows. Thanks a lot!
