### ISSUE TITLE
install IPOPT 

### ISSUE THREAD

**Issue by yunxiaoshan** [udacity/CarND-MPC-Project#14]
I do not know why I can not make successfully, it shows as follows:

> `make[3]: Leaving directory '/home/usi/Downloads/Ipopt-3.12.8/build/Ipopt/src/Apps/CUTErInterface'
make[3]: Entering directory '/home/usi/Downloads/Ipopt-3.12.8/build/Ipopt/src/Apps'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/usi/Downloads/Ipopt-3.12.8/build/Ipopt/src/Apps'
make[2]: Leaving directory '/home/usi/Downloads/Ipopt-3.12.8/build/Ipopt/src/Apps'
make[2]: Entering directory '/home/usi/Downloads/Ipopt-3.12.8/build/Ipopt'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/home/usi/Downloads/Ipopt-3.12.8/build/Ipopt'
make[1]: Leaving directory '/home/usi/Downloads/Ipopt-3.12.8/build/Ipopt'
make[1]: Entering directory '/home/usi/Downloads/Ipopt-3.12.8/build'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/usi/Downloads/Ipopt-3.12.8/build'
my operation system: ubuntu 16.04.
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
GNU Make 4.1

`

**Comment by liuJwei** [comment]
I got the same problem, have you ever solved it?

**Comment by mvirgo** [comment]
We've now added a classroom workspace for this project, so I am closing to close out this ticket.
