### ISSUE TITLE
brew no longer supports ipopt

### ISSUE THREAD

**Issue by BruinBear** [udacity/CarND-MPC-Project#17]
Thus the installation script would not work anymore.
`
brew tap homebrew/science
`
`
Warning: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.
`

**Comment by mvirgo** [comment]
Hi! I've updated the script to be included within our own repo. If you are still having trouble, can you switch it to: `brew tap udacity/CarND-MPC-Project https://github.com/udacity/CarND-MPC-Project`

**Comment by AbhishekGurudutt** [comment]
Hello,
I am getting the following error,

brew install ipopt --with-openblas
==> Installing ipopt from udacity/carnd-mpc-project
Error: No available formula with the name "mumps" (dependency of udacity/carnd-mpc-project/ipopt)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by mvirgo** [comment]
Looks like we need to add the old mumps script too. I will do that within the next day @AbhishekGurudutt

**Comment by AbhishekGurudutt** [comment]
Thank you. Currently, I made it to work by manually compiling all libraries.

**Comment by mvirgo** [comment]
Solved by manually compiling; will continue to monitor in case of continued issues.
