### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by hxlee309** [udacity/CarND-MPC-Project#33]
I have installed all the required dependencies. When I typed "make" in the "build" folder, I got the following error: 

[100%] Linking CXX executable mpc
/usr/local/lib/libipopt.so: undefined reference to `dpotrf_'
/usr/local/lib/libipopt.so: undefined reference to `dgemm_'
/usr/local/lib/libipopt.so: undefined reference to `dnrm2_'
/usr/local/lib/libipopt.so: undefined reference to `dscal_'
/usr/local/lib/libipopt.so: undefined reference to `dpotrs_'
/usr/local/lib/libipopt.so: undefined reference to `dtrsm_'
/usr/local/lib/libipopt.so: undefined reference to `daxpy_'
/usr/local/lib/libipopt.so: undefined reference to `dgetrf_'
/usr/local/lib/libipopt.so: undefined reference to `dcopy_'
/usr/local/lib/libipopt.so: undefined reference to `idamax_'
/usr/local/lib/libipopt.so: undefined reference to `dsyrk_'
/usr/local/lib/libipopt.so: undefined reference to `dasum_'
/usr/local/lib/libipopt.so: undefined reference to `dsyev_'
/usr/local/lib/libipopt.so: undefined reference to `dmumps_c'
/usr/local/lib/libipopt.so: undefined reference to `dgetrs_'
/usr/local/lib/libipopt.so: undefined reference to `ddot_'
/usr/local/lib/libipopt.so: undefined reference to `dsymv_'
/usr/local/lib/libipopt.so: undefined reference to `dgemv_'
collect2: error: ld returned 1 exit status
CMakeFiles/mpc.dir/build.make:120: recipe for target 'mpc' failed
make[2]: *** [mpc] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mpc.dir/all' failed
make[1]: *** [CMakeFiles/mpc.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Any help will be appreciated.

Thanks,

Hanxiang

**Comment by mvirgo** [comment]
I would suggest going back to check the installation for ipopt - it looks like it did not completely link everything correctly. Otherwise, the next best solution would be to use the new project Workspace in the classroom, which has ipopt pre-installed.

**Comment by mvirgo** [comment]
No further responses this past week, so I'm guessing you had this resolved already. Feel free to re-open if needed.
