### ISSUE TITLE
Error while installing Ipopt in Mac

### ISSUE THREAD

**Issue by tamoghna21** [udacity/CarND-MPC-Project#34]
While trying to install Ipopt in Mac 10.13, by giving this command "brew install ipopt --with-openblas", I get the following error:

==> Installing ipopt from udacity/carnd-mpc-project
Error: No available formula with the name "scotch5" (dependency of udacity/carnd-mpc-project/ipopt)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
git -C "$(brew --repo homebrew/core)" fetch --unshallow
Error: No previously deleted formula found.

Any help is appreciated.

Thanks.

**Comment by linghuchong9981** [comment]
I have the same problem,Any help is appreciated.

**Comment by shareq2005** [comment]
Have the same issue :(. Appreciate any help.

**Comment by gallingern** [comment]
macOS 10.13.6
Homebrew 1.7.1-220-g46f531b

```
brew tap udacity/CarND-MPC-Project https://github.com/udacity/CarND-MPC-Project
brew install ipopt --with-openblas
```

```
==> Installing ipopt from udacity/carnd-mpc-project
Error: No available formula with the name "scotch5" (dependency of udacity/carnd-mpc-project/ipopt)
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

```
brew tap brewsci/homebrew-science
brew install scotch5
```

```
Error: Failure while executing; `patch -g 0 -f -p1` exited with 1. Here's the output:
1203
```

**Comment by tamoghna21** [comment]
I found a workaround.

=> brew tap udacity/CarND-MPC-Project https://github.com/udacity/CarND-MPC-Project
=> brew tap brewsci/science https://github.com/brewsci/homebrew-science

Go to /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula , copy scotch.rb and scotch5.rb.
Paste the above two files into /usr/local/Homebrew/Library/Taps/udacity/homebrew-carnd-mpc-project folder
Then:
=> brew untap brewsci/science
=> brew install ipopt --with-openblas

**Comment by mvirgo** [comment]
For now, we are suggesting using the brewsci tap instead of ours if using Mac. Otherwise, we've now added a workspace in the classroom with ipopt pre-installed.

**Comment by LauraLe** [comment]
> I found a workaround.
> 
> => brew tap udacity/CarND-MPC-Project https://github.com/udacity/CarND-MPC-Project
> => brew tap brewsci/science https://github.com/brewsci/homebrew-science
> 
> Go to /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula , copy scotch.rb and scotch5.rb.
> Paste the above two files into /usr/local/Homebrew/Library/Taps/udacity/homebrew-carnd-mpc-project folder
> Then:
> => brew untap brewsci/science
> => brew install ipopt --with-openblas

I follow the above approach. But I cannot find scotch.rb in /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula . Any help is appreciated. 
I am having trouble with install ipopt on Mac.

**Comment by pavelsimo** [comment]
> > I found a workaround.
> > => brew tap udacity/CarND-MPC-Project https://github.com/udacity/CarND-MPC-Project
> > => brew tap brewsci/science https://github.com/brewsci/homebrew-science
> > Go to /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula , copy scotch.rb and scotch5.rb.
> > Paste the above two files into /usr/local/Homebrew/Library/Taps/udacity/homebrew-carnd-mpc-project folder
> > Then:
> > => brew untap brewsci/science
> > => brew install ipopt --with-openblas
> 
> I follow the above approach. But I cannot find scotch.rb in /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula . Any help is appreciated.
> I am having trouble with install ipopt on Mac.

I have the same issue, you can download the missing ```scotch.rb``` in the URL below:
https://raw.githubusercontent.com/dpo/homebrew-openblas/master/Formula/scotch.rb
