### ISSUE TITLE
Failed to listen to port

### ISSUE THREAD

**Issue by hxlee309** [udacity/CarND-MPC-Project#35]
If I terminate the simulation using ctrl-z then re-run the simulation, it will simply returns "failed to listen to port". I wonder if there's any solution to this issue besides reboot. Any help will be appreciated.

**Comment by mvirgo** [comment]
Unfortunately no, you need to re-boot the code and simulator each time around.

**Comment by islammustafa279810** [comment]
> Unfortunately no, you need to re-boot the code and simulator each time around.

Can you explain what I should do in this case
