### ISSUE TITLE
How to set the autonomous mode for MPC controller

### ISSUE THREAD

**Issue by aogrcs** [udacity/CarND-MPC-Project#36]
Hi,
When I start the sim program and mpc program as the attachment. I find that I can control the car using keyboards, but is there any solution about making the car following the path using mpc autonomously? Thanks
![default](https://user-images.githubusercontent.com/5660925/47125728-b0b06b00-d2b7-11e8-931e-c7f461de63ab.JPG)

**Comment by mvirgo** [comment]
Do you mean to actually have paths that it follows? The main thing would typically be to ensure the port 4567 is actually open as instructed in the classroom, otherwise it may be that the messages aren't getting sent out of your code in the way the simulator expects.

**Comment by mvirgo** [comment]
No further responses this past week, so I'm guessing you may have already had this resolved. Closing for now, but feel free to re-open if you are still having issues.

**Comment by vimar-gu** [comment]
Hi there, I cannot start the autonomous mode as well and I cannot enter the classroom cause I don't have the authority maybe? And I checked the port, it seems to have been connected correctly but the car isn't moving. So any advice?
