### ISSUE TITLE
[QUESTION]: Should the FG_eval object be created every time MPC::Solve is called?

### ISSUE THREAD

**Issue by MTDzi** [udacity/CarND-MPC-Project#42]
Hi,

In the `std::vector<double> MPC::Solve(const VectorXd &state, const VectorXd &coeffs)` method there are parts that (I think) can be done once, in the `MPC::MPC` constructor, e.g.:
```
...
 FG_eval fg_eval(coeffs);
...
```

Is there a reason for this?

**Comment by mvirgo** [comment]
I don't have enough insight here on how ipopt's `solve` function operates to answer this exactly. The code here is basically a modified version of how it is presented [here](https://www.coin-or.org/CppAD/Doc/ipopt_solve_get_started.cpp.htm), which similarly creates the object each time. 

My thinking is that it *would* likely be more efficient to just update the coefficients within the object each time, while creating the object in the constructor (or some other initialization function). This is based on ipopt's `solve` likely calling the `operator` function in `fg_eval` each time, so as long as the coefficients are updated between rounds, it would still operate fine. I'll test this out more and see if it works the same way.

**Comment by MTDzi** [comment]
Hey,

Thanks for answering :+1: 
I was meaning to test this out myself, but ultimately -- didn't.
However, if I'll manage to find the time to check this I'll leave a comment here.

**Comment by mvirgo** [comment]
So after some further testing, we'll probably just leave as is - looks like it is a decent pain to re-configure this to avoid re-initializing the object each time (basically have to make the object part of the MPC class itself), and the actual initialization doesn't cause much of a slowdown speed wise (takes 0-1 microseconds). There could be a memory issue there if this was run for a long time, but I didn't notice anything while running a lap or two at a time.

Again though, your thinking is definitely solid in that overall it's not really necessary to do every single time.
