### ISSUE TITLE
Issue when building Ipopt-3.12.x

### ISSUE THREAD

**Issue by vuonglq-vn** [udacity/CarND-MPC-Project#9]
Hi @baumanab , @domluna ,

In your [Readme](https://github.com/udacity/CarND-MPC-Project/blob/master/README.md) give an instruction for install Ipopt:

* You just need to download the source from the Ipopt [releases page](https://www.coin-or.org/download/source/Ipopt/) or the [Github releases](https://github.com/coin-or/Ipopt/releases) page.

And I saw that the Ipopt [releases page](https://www.coin-or.org/download/source/Ipopt/) or the [Github releases](https://github.com/coin-or/Ipopt/releases) page have a little different.

![capture](https://user-images.githubusercontent.com/11450887/29082761-ae106284-7c90-11e7-95d1-a0e2c4c1bf41.PNG)

* Ipopt [releases page](https://www.coin-or.org/download/source/Ipopt/): build with script `install_ipopt.sh` success

* [Github releases](https://github.com/coin-or/Ipopt/releases): build error because it lack `ThirdParty` and `BuildTools` folder

Maybe someone will have this issue and take a lot of time to correct it.
So if possible, please consider to update this information into your instruction.

**Comment by feichashao** [comment]
+1. I also encounter the same issue while I am install Ipopt-3.12.1. 
The Github release failed, and Ipopt release page succeed.

**Comment by domluna** [comment]
Hey guys, I thought I deleted the Github release page already, guess I didn't! Anyway I removed the link to it, not sure why the zip files are different.
